### ISSUE TITLE
Flowchart

### ISSUE THREAD

**Issue by PecoPeterson** [PecoPeterson/special-word#6]
A proper flowchart would make the code easier to understand not just for those who want to work on the code, but also for those who want to use the code and understand it better.

**Comment by XxxOnigiriKittenxxX** [comment]
Goedenavond, dit is de comment op de flowchart

**Comment by PecoPeterson** [comment]
Made a flowchart, should be fine
![flowchart](https://user-images.githubusercontent.com/82600424/213873644-c00f8745-7c7c-411e-b93d-5fbc3ffb9b08.png)
